apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: thamako3/pnregistry-ufe
  newName: thamako3/pnregistry-ufe
  newTag: 1.0.1  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
- name: thamako3/pnregistry-webapi
  newName: thamako3/pnregistry-webapi
  newTag: 1.0.1

replacements:
 - targets:
   - select:
         group: fe.milung.eu
         version: v1
         kind: WebComponent
         name: mb-pnregistry-ufe
     fieldPaths:
         - spec.hash-suffix
   source:
     version: v1
     kind: Deployment
     name:  mb-pnregistry-ufe-deployment
     fieldPath: spec.template.spec.containers.0.image
     options:
         delimiter: ':'
         index: 1