apiVersion: apps/v1
kind: Deployment
metadata:
  name: mb-pnregistry-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /mb-openapi
            - name: BASE_URL
              value: /mb-openapi-ui